config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
   }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  resources :users
  resources :basics
  resources :specials
  resources :lanks
end

app/models/basic.rb
class Basic < ApplicationRecord
  validates :name, :number, presence: true
  validates :name, length: { maximum: 6 }
  validates :number, numericality: {less_than: 101}
  has_many :users
end

app/controllers/basics_controller.rb
class BasicsController < ApplicationController

  def index
  end

  def new
    @basic = Basic.new
    @basics = Basic.all
  end

  def create
    basic = Basic.new(post_params)
    basic_record =Basic.find_by(name: basic.name,user_id: current_user.id)
    user = User.find(current_user.id)
    if user.basics.count < 6
      if basic_record.blank?
        if basic.save
          redirect_to new_basic_path
          flash[:success] = "基礎能力「#{basic.name}」を追加しました。"
        else
          redirect_to new_basic_path
          flash[:delete] = '基礎能力を追加できませんでした。６文字以下だったか、数値が100以下だったか・空欄・重複がなかったか。もう一度やってみてね。'
        end
      else
        redirect_to new_basic_path
        flash[:delete] = '基礎能力を追加できませんでした。同じ名前の基礎能力は登録できません・・・。'
      end
    else
      redirect_to new_basic_path
      flash[:delete] = '基礎能力を追加できませんでした。登録できる基礎能力は6つまでです。能力を１つ削除してから再登録してください。'
    end

  end


  def edit
    @basics = Basic.find(params[:id])
    @@basic_before = Basic.find(params[:id])
  end


  def update
    @basics = Basic.find(params[:id])
    check_params = Basic.new(post_params)
    basic_record = Basic.where(name: check_params.name,user_id: current_user.id) #存在する。＝変更後の名前が同じものがあるor名前を変更していない
    if basic_record.present? #同一ユーザー内で変更後の基礎能力名が存在している時
      if check_params.name == @basics.name && check_params.number == @basics.number #名称・数値が変更されていない時
        redirect_to user_path(current_user.id)
      elsif check_params.name == @basics.name && check_params.number != @basics.number #名称が変更されず、数値が変更された時
        if @basics.update(post_params)#値を更新できるか判断する。できた場合
          redirect_to user_path(current_user.id)
          flash[:success] = "基礎能力「#{@basics.name}」の数値を#{@@basic_before.number}から#{check_params.number}に変更しました。"
        else#値を更新できるか判断する。できなかった場合。
          redirect_to user_path(current_user.id)
          flash[:delete] = '基礎能力を更新できませんでした。数値が100以下だったか・空欄ではなかったか、確かめてみてね。'#文字数・数値の範囲で弾かれていることが想定される。
        end
      else#変更された名称が同一ユーザー内の基礎能力名と同じだった場合
        redirect_to user_path(current_user.id)
        flash[:delete] = '基礎能力を更新できませんでした。同じ名前の能力は登録できません・・・'
      end
    else#存在していない時
      if check_params.name != @basics.name && check_params.number != @basics.number #名称・数値が変更された時
        if @basics.update(post_params)#値を更新できるか判断する。できた場合
          redirect_to user_path(current_user.id)
          flash[:success] = "基礎能力名を「#{@@basic_before.name}」から「#{@basics.name}」に、数値を#{@@basic_before.number}から#{@basics.number}に変更しました。"#数値と名称変更
        else#値を更新できるか判断する。できなかった場合。
          redirect_to user_path(current_user.id)
          flash[:delete] = '基礎能力を更新できませんでした。文字数や数値に間違いはないか、確かめてみてね。'#文字数・数値の範囲で弾かれていることが想定される。
        end
      else
        if @basics.update(post_params)#値を更新できるか判断する。できた場合
          redirect_to user_path(current_user.id)
          flash[:success] = "基礎能力名を「#{@@basic_before.name}」から「#{@basics.name}」に変更しました。"#名称変更
        else#値を更新できるか判断する。できなかった場合。
          redirect_to user_path(current_user.id)
          flash[:delete] = '基礎能力を更新できませんでした。文字数が６文字以下か、空欄ではなかったか、もう一度やってみてね。'#文字数・数値の範囲で弾かれていることが想定される。
        end
      end
    end
  end

  def destroy
    @basics = Basic.find(params[:id])
    path = Rails.application.routes.recognize_path(request.referer)
    
    if path[:controller] == "users" && path[:action] == "show"
      @basics.destroy
      redirect_to user_path(current_user.id)
      flash[:delete] = "基礎能力「#{@basics.name}」を削除しました"
    else
      @basics.destroy
      redirect_to new_basic_path
      flash[:delete] = "基礎能力「#{@basics.name}」を削除しました"
    end

  end

  def show
    @basics = Basic.find(params[:id])
  end

  private
  def post_params
    params.require(:basic).permit(:name,:number).merge(user_id: current_user.id)
  end

end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/views/basics/_basic.haml
-@basics.each do |basic|
  %tr
  -if current_user.id == basic.user_id
    .index
      .index__ability__name
        = basic.name
        <br>
        - i = basic.number
        -if i >= 90 && i <101
          = image_tag src="/assets/S.png", size: "100x50"
        -elsif i >= 80 && i <90
          = image_tag src="/assets/A.png", size: "100x50"
        -elsif i >= 70 && i <80
          = image_tag src="/assets/B.png", size: "100x50"
        -elsif i >= 60 && i <70
          = image_tag src="/assets/C.png", size: "100x50"
        -elsif i >= 50 && i <60
          = image_tag src="/assets/D.png", size: "100x50"
        -elsif i >= 40 && i <50
          = image_tag src="/assets/E.png", size: "100x50"
        -elsif i >= 20 && i <40
          = image_tag src="/assets/F.png", size: "100x50"
        -elsif i >= 0 && i <20
          = image_tag src="/assets/G.png", size: "100x50"
        - else
          %p ???
      .index__ability__number
        = basic.number
      .index__ability__edit
        =link_to "編集",edit_basic_path(basic.id) ,method: :get,class:"link__edit"
        •
        =link_to "削除","/basics/#{basic.id}",method: :delete,class:"link__edit"

app/views/basics/_show.haml
-@basics.each do |basic|
  %tr
  -if current_user.id == basic.user_id
    .index
      .index__ability__name
        = basic.name
        <br>
        - i = basic.number
        -if i >= 90 && i <101
          = image_tag src="/assets/S.png", size: "100x50"
        -elsif i >= 80 && i <90
          = image_tag src="/assets/A.png", size: "100x50"
        -elsif i >= 70 && i <80
          = image_tag src="/assets/B.png", size: "100x50"
        -elsif i >= 60 && i <70
          = image_tag src="/assets/C.png", size: "100x50"
        -elsif i >= 50 && i <60
          = image_tag src="/assets/D.png", size: "100x50"
        -elsif i >= 40 && i <50
          = image_tag src="/assets/E.png", size: "100x50"
        -elsif i >= 20 && i <40
          = image_tag src="/assets/F.png", size: "100x50"
        -elsif i >= 0 && i <20
          = image_tag src="/assets/G.png", size: "100x50"
        - else
          %p ???
      .index__ability__number
        = basic.number

app/views/basics/edit.haml
.edit
  %h1 Edit Basic Ability Form
  .edit__index
    .edit__index__basic-ability
      %h2 基礎能力を編集しよう！
      = form_with model: @basics,local: true do |f|
        = f.text_field :name,class:"edit__index__basic-ability__form"
        = f.number_field :number,class:"edit__index__basic-ability__number"
        <br>
        = f.submit '決定！',class:"edit__index__basic-ability__btn"
 

  =link_to "戻る",user_path(current_user.id),method: :get,class:"back-link"

app/views/basics/index.haml
.header
  .header__top
    データあれこれ
.menu
  %h1 めにゅ〜
  .menu_index
    =link_to "能力が選ばれてる数",lanks_path
  -if user_signed_in?
    =link_to "あなたの能力評価", lank_path(current_user.id)

app/views/basics/new.haml
.flash
  = flash[:success]
.good
  = flash[:good]
.delete
  = flash[:delete]
.basic
  %h1 Basic Ability Form
  .basic__index
    .basic__index__basic-ability
      %h2 基礎能力を入力しよう！
      = form_with model: @basic,local: true do |f|
        = f.select :name, [["能力を選んでね。",""],["コミュ力","コミュ力"],["企画力","企画力"],["明るさ","明るさ"],["気遣い力","気遣い力"],["モテ力","モテ力"],["気が利く","気が利く"],["真面目度","真面目度"],["共感力","共感力"],["貯蓄","貯蓄"],["幸福度","幸福度"],["面白さ","面白さ"]],class:"basic__index__basic-ability__form"
        <br>
        = f.number_field :number,placeholder:"数値(0~100)",class:"basic__index__basic-ability__number"
        <br>
        = f.submit '基礎能力を追加する！',class:"basic__index__basic-ability__btn"
    .basic__index__original-ability
      %h2 オリジナル能力はこちらから！
      = form_with model: @basic,local: true do |f|
        = f.text_field :name,placeholder:"能力名",class:"basic__index__original-ability__name"
        <br>
        = f.number_field :number,placeholder:"数値(0~100)",class:"basic__index__original-ability__number"
        <br>
        = f.submit 'オリジナル能力を追加する！',class:"basic__index__original-ability__btn"
        <br>
  .basic__form
    %h3
      プレビュー
    .index__ability
      = render'/basics/basic'
  =link_to "作成画面に戻る",user_path(current_user.id),method: :get,class:"back-link"