config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
   }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  resources :users
  resources :basics
  resources :specials
  resources :lanks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, ImagesUploader
  has_many :basics
  has_many :specials
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  @user = nil
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only:[:edit,:show]

  def index
  end

  def create
    User.create(post_params)
    redirect_to user_path(current_user.id)
  end

  def edit
  end

  def update
    user = User.find(params[:id])
    user.update(post_params)
    redirect_to user_path(current_user.id)
  end

  def show
    @specials = Special.all
    @basics = Basic.all
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to user_path(current_user.id)
  end

  private
  def post_params
    params.require(:user).permit(:nickname,:image)
  end

  def set_user
    @user = User.find(params[:id])
  end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_header.haml
.header
  .header__title
    =link_to"Pawa-syoukai",root_path
    - if user_signed_in?
      .header__title__new
        =link_to "新規作成" , user_path(current_user.id)
      .header__title__show
        =link_to "作った選手を見る" , specials_path
      -# .header__title__index
      -#   =link_to "データあれこれ" , basics_path
      .header__title__sign-out
        =link_to "ログアウト" , destroy_user_session_path,method: :delete
        
    - else
      .header__title__sign-in
        =link_to "ログイン" , new_user_session_path
      .header__title__sign-up
        =link_to "新規登録（まずはここから）" ,  new_user_registration_path
      -# .header__title__index
      -#   =link_to "データあれこれ" , basics_path

app/views/users/_how_to.html.haml
.howto-main
  .howto-main__notise
    %h1
      新しい
      <br>
      自己紹介のカタチ
    %h2
      自己紹介アプリ「Pawa-shoukai」では、
      %span.howto-main__notise__basic 項目名と数値
      を使って自分を可視化させることができます。
      <br>
      特殊能力を使ってさらなる個性を追加することも可能！
      <br>
      初期設定されている項目だけでなく、
      %span.howto-main__notise__special オリジナル項目
      を設定することもできます！
      <br>
      得意なこと、お茶目な側面をサクッっと！楽しく！アピールしてみませんか？
    = image_tag "sample1.png",size: "600x250", class: "howto-main__notise__first"
  .howto-main__img
    = image_tag "sample2.png",size: "600x250", class: "howto-main__img__second"

app/views/users/edit.haml
.user
  .user__index
    %h1 ユーザー情報の変更
    = form_with model: @user,local: true do |f|
      .user__index__name
        %i.fas.fa-user.fa-fw
        = f.text_field :nickname,placeholder:"Name",class:"user__index__name__form"
      .user__index__image
        %i.fas.fa-camera-retro.fa-fw
        = f.file_field :image,placeholder:"image",class:"user__index__image__form"
      -if @user.image
        .user__index__view
          %h3
            <現在の画像>
          =image_tag"#{@user.image.url}",class:".user__index__view__img"
          <br>
          %i.user__index__view__arrow.fas.fa-arrow-down
          %i.user__index__view.fas.fa-arrow-down
          %i.user__index__view__icon.fas.fa-arrow-down
        .user__index__preview


      .user__index__btn
        = f.submit '変更！！'
      <br>
  =link_to "作成画面に戻る",user_path(current_user.id),method: :get,class:"user__back"

app/views/users/index.haml
= render 'header'
= render 'how_to'

app/views/users/show.haml
= render partial:'/users/header'
.flash
  = flash[:success]
.good
  = flash[:good]
.delete
  = flash[:delete]
.wrapper
  .side-bar
    入力フォーム
    .list
      %li
        -if @user.basics.count < 6
          =link_to "基礎能力を決める",new_basic_path,class:"list__basic"
        - else
          %h1.list__notise
            基礎能力は6個まで！
            <br>
            削除ボタンで削除してね
      %li
        -if @user.specials.count < 16
          =link_to "特殊能力を作る",new_special_path,class:"list__special"
        - else
          %h1.list__notise
            特殊能力は16個まで！
            <br>
            削除ボタンで削除してね 
  .main-view
    .status
      .status__name
        =current_user.nickname
        <br>
        .status__name__edit
          =link_to "編集",edit_user_path(current_user.id),method: :get,class:"link__edit"
      .status__image
        = image_tag src=current_user.image.to_s, size: "200x200"
      .index__ability
        = render partial:'/basics/basic',basics: @basics
    .special
      = render partial:'/specials/special',specials: @specials