config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
   }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  resources :users
  resources :basics
  resources :specials
  resources :lanks
end

app/models/special.rb
class Special < ApplicationRecord
  validates :name, presence: true, length: { maximum: 10 }
  has_many :users
end

app/controllers/specials_controller.rb
class SpecialsController < ApplicationController
  
  def index
    @basics = Basic.all
    @users = User.all
    @specials = Special.all
  end

  def new
    @special = Special.new
    @specials = Special.all

  end

  def create
    special = Special.new(post_params)
    special_record =Special.find_by(name: special.name,user_id: current_user.id)
    user = User.find(current_user.id)
    if user.specials.count < 16
      if special_record.blank? && special.save 
        redirect_to new_special_path
        flash[:success] = "特殊能力「#{special.name}」を追加しました"
      else
        redirect_to new_special_path
        flash[:delete] = '特殊能力を追加できませんでした。ボタンが正しく選べているか・重複がないか・１０文字以内か確かめてもう一度やってみてね'
      end
    else
      redirect_to new_special_path
      flash[:delete] = "特殊能力を追加できませんでした。登録できる特殊能力は16個までです。"
    end

  end

  def destroy
    @specials = Special.find(params[:id])
    path = Rails.application.routes.recognize_path(request.referer)
    if path[:controller] == "users" && path[:action] == "show"
      @specials.destroy
      redirect_to user_path(current_user.id)
      flash[:delete] = "特殊能力「#{@specials.name}」を削除しました"
    else
      @specials.destroy
      redirect_to new_special_path
      flash[:delete] = "特殊能力「#{@specials.name}」を削除しました"
    end
    
  end


  private
  def post_params
    params.require(:special).permit(:name).merge(user_id: current_user.id)
  end
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/views/specials/_special.html.haml
-@specials.each do |special|
  -if current_user.id == special.user_id
    .special__original
      =special.name
      <br>
      =link_to "削除",special_path(special.id),method: :delete,class:"special__original__delete"
  -else

app/views/specials/index.haml
= render partial:'/users/header'
.center-format
  .wrapper
    .main-view
      .status
        .status__name
          =current_user.nickname
          <br>
        .status__image
          = image_tag src=current_user.image.to_s, size: "200x200"
        .index__ability
          = render partial:'/basics/show',basic: @basics
      .special
        -@specials.each do |special|
          -if current_user.id == special.user_id
            .special__original
              =special.name
          -else

app/views/specials/new.haml
.flash
  = flash[:success]
.delete
  = flash[:delete]
.new-special
  %h1 Special Ability Form
  .new-special__index
    .new-special__index__special-ability
      %h2 特殊能力を選ぼう！
      = form_with model: @special, local: true do |f|
        = f.select :name, [["能力を選んでね。",""],["対ピンチ○","対ピンチ○"],["対変な人○","対変な人○"],["ムードメーカー","ムードメーカー"],["満員電車○","満員電車○"],["集中力","集中力"],["気が利く","気が利く"],["調子安定","調子安定"],["多趣味","多趣味"],["家計管理○","家計管理○"],["コミュニケーション○","コミュニケーション○"],["月曜日○","月曜日○"]],class:"new-special__index__special-ability__form"
        <br>
        = f.submit '特殊能力を追加する！',class:"new-special__index__special-ability__btn"
    .new-special__index__original-ability
      %h2 オリジナル能力はこちらから！
      = form_with model: @special, local: true do |f|
        = f.text_field :name,placeholder:"10文字以内で作ってね",id: "original-name",class:"new-special__index__original-ability__form"
        <br>
        = f.submit 'オリジナル特殊能力を追加する！',class:"new-special__index__original-ability__btn"
        <br>
  .new-special__form
    %h3
      プレビュー
    .new-special__form__index
      = render'/specials/special'
  =link_to "戻る",user_path(current_user.id),method: :get,class:"back-link"